"""
BitHub V2 — db_ingest.py
Universal database ingestion script.
  - Reads normalized JSONs from normalized_questions/
  - Reads answer JSONs from answers/
  - Auto-detects subject/subject_code from the data
  - Builds INSERT SQL and executes via SSH → sudo mysql
  - All credentials from .env — never hardcoded
"""

import json
import time
import os
import sys
from pathlib import Path
import paramiko
from dotenv import load_dotenv

# ------------------------------------------------------------------
# CONFIGURATION
# ------------------------------------------------------------------
BASE_DIR       = Path(__file__).parent
NORM_DIR       = BASE_DIR / "normalized_questions"
ANSWERS_DIR    = BASE_DIR / "answers"

load_dotenv(BASE_DIR / ".env")
SSH_HOST        = os.getenv("DB_SSH_HOST")
SSH_USER        = os.getenv("DB_SSH_USER")
SSH_PASS        = os.getenv("DB_SSH_PASS")
DB_NAME         = os.getenv("DB_NAME", "questions")
REMOTE_SQL_PATH = "/tmp/bithub_ingest.sql"

if not all([SSH_HOST, SSH_USER, SSH_PASS]):
    raise ValueError(
        "Missing required environment variables. "
        "Check your .env file (see .env.example)."
    )

# ------------------------------------------------------------------
# SQL HELPERS
# ------------------------------------------------------------------

def esc(val) -> str:
    """Escape a Python value to a MySQL string literal or NULL."""
    if val is None:
        return "NULL"
    s = str(val)
    s = s.replace("\\", "\\\\")
    s = s.replace("'",  "\\'")
    s = s.replace("\0", "\\0")
    s = s.replace("\n", "\\n")
    s = s.replace("\r", "\\r")
    return f"'{s}'"


def derive_difficulty(marks) -> str:
    if marks is None:
        return "NULL"
    m = int(marks)
    if m <= 2:
        return "'easy'"
    elif m == 3:
        return "'medium'"
    else:
        return "'hard'"


def build_sql_file(
    questions: list,
    solutions_map: dict,
    subject: str,
    subject_code: str,
    sql_path: Path,
) -> None:
    print("  Building INSERT SQL file...")
    lines = [
        f"-- BitHub V2 INSERT — {subject_code} ({subject})",
        f"-- Generated by db_ingest.py",
        "",
    ]

    for q in questions:
        uid  = q.get("question_uid", "")
        sol  = solutions_map.get(uid, {})
        tags = (
            json.dumps(q.get("tags", []), ensure_ascii=False)
            if q.get("tags") is not None
            else None
        )

        lines.append(
            "INSERT INTO questions ("
            "question_uid,exam,subject,subject_code,module,year,"
            "question_number,question_text,question_latex,"
            "solution_text,solution_latex,final_answer,"
            "tags,question_type,confidence_score,"
            "is_verified,latex_valid,generated_by,marks,difficulty"
            ") VALUES ("
            f"{esc(uid)},"
            f"{esc(q.get('source_exam'))},"
            f"{esc(subject)},"
            f"{esc(subject_code)},"
            f"{esc(str(q.get('module_number', '')))},"
            f"{esc(q.get('source_year'))},"
            f"{esc(q.get('question_number'))},"
            f"{esc(q.get('question_text'))},"
            f"{esc(q.get('question_latex'))},"
            f"{esc(sol.get('solution_text'))},"
            f"{esc(sol.get('solution_latex'))},"
            f"{esc(sol.get('final_answer'))},"
            f"{esc(tags)},"
            f"{esc(q.get('question_type'))},"
            f"{esc(sol.get('confidence_score'))},"
            f"{int(q.get('is_verified', False))},"
            f"{int(q.get('latex_valid', True))},"
            f"{esc(sol.get('generated_by'))},"
            f"{esc(q.get('marks'))},"
            f"{derive_difficulty(q.get('marks'))}"
            ") ON DUPLICATE KEY UPDATE "
            "solution_text=VALUES(solution_text),"
            "solution_latex=VALUES(solution_latex),"
            "final_answer=VALUES(final_answer),"
            "confidence_score=VALUES(confidence_score),"
            "generated_by=VALUES(generated_by);"
        )

    sql_path.write_text("\n".join(lines), encoding="utf-8")
    size_kb = sql_path.stat().st_size / 1024
    print(f"  ✓ {sql_path.name} ({size_kb:.1f} KB, {len(questions)} inserts)")

# ------------------------------------------------------------------
# SSH HELPERS
# ------------------------------------------------------------------

def shell_send(shell, cmd: str, wait: float = 1.5) -> str:
    shell.send(cmd + "\n")
    time.sleep(wait)
    out = ""
    while shell.recv_ready():
        out += shell.recv(65536).decode("utf-8", errors="replace")
    return out

# ------------------------------------------------------------------
# FILE PICKER
# ------------------------------------------------------------------

def pick_file(directory: Path, prompt: str, pattern: str = "*.json") -> Path:
    files = sorted(directory.glob(pattern))
    if not files:
        print(f"[ERROR] No matching files in {directory}")
        sys.exit(1)

    print(f"\n{prompt}")
    for i, f in enumerate(files, 1):
        print(f"  [{i}] {f.name}")

    while True:
        try:
            choice = int(input("\nEnter number: ").strip())
            if 1 <= choice <= len(files):
                return files[choice - 1]
        except (ValueError, KeyboardInterrupt):
            pass
        print(f"  Please enter a number between 1 and {len(files)}.")

# ------------------------------------------------------------------
# MAIN
# ------------------------------------------------------------------

def main():
    print("=" * 55)
    print("BitHub V2 — Universal DB Ingestion")
    print("=" * 55)

    # --- Pick normalized question file ---
    if len(sys.argv) > 1:
        norm_path = Path(sys.argv[1])
        if not norm_path.is_absolute():
            norm_path = NORM_DIR / norm_path
    else:
        norm_path = pick_file(
            NORM_DIR,
            "Select a normalized question JSON to ingest:",
        )

    if not norm_path.exists():
        print(f"[ERROR] File not found: {norm_path}")
        sys.exit(1)

    with open(norm_path, encoding="utf-8") as f:
        questions = json.load(f)

    if not questions:
        print("[ERROR] No questions found.")
        sys.exit(1)

    # Auto-detect subject from data
    subject      = questions[0].get("subject",      "Unknown Subject")
    subject_code = questions[0].get("subject_code", "UNKNOWN")

    # --- Find corresponding answers file ---
    # stem e.g. "PH24101_Derivation_normalized" → "PH24101_Derivation"
    stem         = norm_path.stem.replace("_normalized", "")
    answers_path = ANSWERS_DIR / f"{stem}_answers.json"

    if answers_path.exists():
        with open(answers_path, encoding="utf-8") as f:
            solutions_raw = json.load(f)
        solutions_map = {s["question_uid"]: s for s in solutions_raw if "question_uid" in s}
    else:
        print(f"  [WARN] No answers file found at {answers_path.name}. "
              "Questions will be inserted without solutions.")
        solutions_map = {}

    print(f"\n  Normalized file : {norm_path.name}")
    print(f"  Answers file    : {answers_path.name if answers_path.exists() else '(not found)'}")
    print(f"  Subject         : {subject} ({subject_code})")
    print(f"  Questions       : {len(questions)}")
    print(f"  Solutions       : {len(solutions_map)}\n")

    sql_path = BASE_DIR / f"{subject_code}_ingest.sql"
    build_sql_file(questions, solutions_map, subject, subject_code, sql_path)

    # --- SSH connection ---
    print(f"\n  SSH → {SSH_HOST} ...")
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(SSH_HOST, username=SSH_USER, password=SSH_PASS, timeout=15)
    print("  Connected.\n")

    # Upload SQL
    print(f"  Uploading SQL to {REMOTE_SQL_PATH} ...")
    sftp = ssh.open_sftp()
    sftp.put(str(sql_path), REMOTE_SQL_PATH)
    sftp.close()
    print("  Uploaded.\n")

    # Interactive shell
    shell = ssh.invoke_shell()
    time.sleep(1)
    shell.recv(65536)

    print("  Entering sudo mysql session ...")
    shell_send(shell, f"sudo mysql {DB_NAME}", wait=1.5)
    shell_send(shell, SSH_PASS, wait=3)

    # Verify we reached mysql>
    probe = shell_send(shell, "", wait=1)
    if "mysql>" not in probe:
        print(f"  [ERROR] Could not reach mysql> prompt. Output:\n{probe}")
        ssh.close()
        sys.exit(1)

    print("  mysql shell active.\n")

    # --- Schema check & ALTER TABLE ---
    cols_raw = shell_send(shell, "SHOW COLUMNS FROM questions;", wait=2)
    existing_cols: set[str] = set()
    for line in cols_raw.splitlines():
        if "|" in line:
            parts = [p.strip() for p in line.split("|")]
            if len(parts) > 1 and parts[1] and parts[1] != "Field" \
                    and not parts[1].startswith("-"):
                existing_cols.add(parts[1])
    print(f"  Existing columns: {sorted(existing_cols)}")

    new_columns = [
        ("question_uid",     "VARCHAR(64) AFTER id"),
        ("subject_code",     "VARCHAR(50) AFTER subject"),
        ("question_latex",   "LONGTEXT AFTER question_text"),
        ("solution_latex",   "LONGTEXT AFTER solution_text"),
        ("final_answer",     "TEXT AFTER solution_latex"),
        ("tags",             "JSON AFTER final_answer"),
        ("question_type",    "VARCHAR(50) AFTER tags"),
        ("confidence_score", "FLOAT AFTER question_type"),
        ("is_verified",      "TINYINT(1) DEFAULT 0 AFTER confidence_score"),
        ("latex_valid",      "TINYINT(1) DEFAULT 1 AFTER is_verified"),
        ("generated_by",     "VARCHAR(100) AFTER latex_valid"),
    ]

    print("  Running ALTER TABLE (skipping existing columns) ...")
    for col, defn in new_columns:
        if col in existing_cols:
            print(f"    SKIP (exists): {col}")
            continue
        out_a = shell_send(shell, f"ALTER TABLE questions ADD COLUMN {col} {defn};", wait=3)
        errs  = [l for l in out_a.splitlines() if "error" in l.lower()]
        print(f"    {'FAIL ' + errs[0][:80] if errs else 'OK: + ' + col}")

    if "question_uid" not in existing_cols:
        idx_out = shell_send(
            shell,
            "CREATE UNIQUE INDEX uniq_uid ON questions (question_uid);",
            wait=2
        )
        print(
            "    OK: UNIQUE INDEX"
            if "error" not in idx_out.lower()
            else f"    WARN index: {idx_out[:80]}"
        )

    # Final schema check
    chk = shell_send(shell, "SHOW COLUMNS FROM questions LIKE 'question_uid';", wait=2)
    if "question_uid" not in chk:
        print("\n  [FATAL] question_uid still missing. Aborting.")
        shell_send(shell, "exit;", wait=1)
        ssh.close()
        sys.exit(1)
    print("  Schema OK.\n")

    # --- Source SQL ---
    print("  Sourcing INSERT statements ...")
    out = shell_send(shell, f"source {REMOTE_SQL_PATH};", wait=25)
    lines = [l for l in out.splitlines() if l.strip() and "password" not in l.lower()]
    print("\n".join(lines[-20:]) if lines else "  (silent)")

    # --- Validate ---
    print("\n  Validating ...")
    for stmt in [
        f"SELECT COUNT(*) AS total FROM questions WHERE subject_code='{subject_code}';",
        f"SELECT exam, year, COUNT(*) n FROM questions WHERE subject_code='{subject_code}' "
        f"GROUP BY exam, year ORDER BY year, exam;",
        f"SELECT difficulty, COUNT(*) n FROM questions WHERE subject_code='{subject_code}' "
        f"GROUP BY difficulty;",
    ]:
        out = shell_send(shell, stmt, wait=3)
        clean = "\n".join(
            l for l in out.splitlines()
            if l.strip() and "password" not in l.lower()
        )
        if clean.strip():
            print(clean)

    # --- Cleanup ---
    shell_send(shell, "exit;", wait=1)
    shell_send(shell, f"rm -f {REMOTE_SQL_PATH}", wait=1)
    shell.close()
    ssh.close()

    print(f"\n  ✓ Ingestion complete for {subject} ({subject_code})")
    print("  Done.\n")


if __name__ == "__main__":
    main()
